### ISSUE TITLE
list-all-nfts-from-wallet  List all NFTs

### ISSUE THREAD

**Issue by itmilos** [Shyft-to/example-projects#1]
List all NFTs for 'mainnet-beta' will display only NFT created with Shyft, it will not list other NFTs from my wallet

**Comment by codinpsycho** [comment]
@itmilos Hey just pushed a commit, it was fetching only those nfts whose update_authority was same as the wallet address. Can you pull and try again? It should fetch all nfts now.

**Comment by itmilos** [comment]
@codinpsycho  Will do, but I have tried it without update_authority but it was the same will try again

**Comment by codinpsycho** [comment]
Oh, do let me know if it persists, we have also deployed a better version of the sample project here https://solana-nft-project-nine.vercel.app/
